### ISSUE TITLE
Should make jsdom a peer dependency

### ISSUE THREAD

**Issue by kmudrick** [TimothyRHuertas/normalizer#5]
Using node 5 & npm 3 - html-normalizer tries to use old jsdom which uses contextify which npm3 tries to compile when it flattens it

**Comment by wolfgang42** [comment]
I just ran into this same problem&mdash;I can't install `contextify` because it's not compatible with my version of node. I thought it would make sense to just declare `"jsdom": ">=3.1.2 <10.0.0"`, but then I tried it with various versions:

``` bash
for ver in \
         4.0.0  5.0.0  6.0.0  7.0.0  8.0.0  9.0.0 \
        ^4.0.0 ^5.0.0 ^6.0.0 ^7.0.0 ^8.0.0 ^9.0.0; do
    echo TEST: jsdom@$ver
    npm install jsdom@$ver
    node_modules/karma/bin/karma start --single-run --browsers Chrome
done
```

Of these versions, `8.0.0`,  `^4.0.0`, and  `^7.0.0` fail (the rest succeed). I have not looked into these failures closely but it seems that support is somewhat lumpy across this broad range.

**Comment by TimothyRHuertas** [comment]
Shoot me a pull request and I'll deploy a new version.

**Comment by wolfgang42** [comment]
What should the PR include, a peer dependency or a regular dependency? What should I use for the version range?

**Comment by TimothyRHuertas** [comment]
Version 7 published.  Thanks for the contribution.
